// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw-6SNZjqtWjxW5sDFjMxvT-cC7F7hQ1Q',
    appId: '1:303684659729:web:6ad63db5fdb8b9c2a0dfb0',
    messagingSenderId: '303684659729',
    projectId: 'naqusta',
    authDomain: 'naqusta.firebaseapp.com',
    storageBucket: 'naqusta.firebasestorage.app',
    measurementId: 'G-CL3PW6HLZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQbJ6L8Nw1hZ7hFbLkZdh813GEM97k6Ik',
    appId: '1:303684659729:android:cc55d6792d4983e4a0dfb0',
    messagingSenderId: '303684659729',
    projectId: 'naqusta',
    storageBucket: 'naqusta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL-d2EVXR4ePhwwpc-5TYKt0y_Qywc81I',
    appId: '1:303684659729:ios:6400a5367d72a5e2a0dfb0',
    messagingSenderId: '303684659729',
    projectId: 'naqusta',
    storageBucket: 'naqusta.firebasestorage.app',
    iosBundleId: 'com.example.kurylKz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL-d2EVXR4ePhwwpc-5TYKt0y_Qywc81I',
    appId: '1:303684659729:ios:6400a5367d72a5e2a0dfb0',
    messagingSenderId: '303684659729',
    projectId: 'naqusta',
    storageBucket: 'naqusta.firebasestorage.app',
    iosBundleId: 'com.example.kurylKz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw-6SNZjqtWjxW5sDFjMxvT-cC7F7hQ1Q',
    appId: '1:303684659729:web:8018fd3a51ff0153a0dfb0',
    messagingSenderId: '303684659729',
    projectId: 'naqusta',
    authDomain: 'naqusta.firebaseapp.com',
    storageBucket: 'naqusta.firebasestorage.app',
    measurementId: 'G-KQRWKRS3MV',
  );

}